### ISSUE TITLE
chron.com

### ISSUE THREAD

**Issue by smed79** [gorhill/uBO-Extra#100]
Hi,
please check `chron.com` for possible Instart Logic script.

source https://forums.lanik.us/viewtopic.php?f=62&t=41482

**Comment by mapx-** [comment]
yeah, is infested (us ip)

![image](https://user-images.githubusercontent.com/10303732/44429416-ac0d5600-a597-11e8-903f-9aca5b95cdf9.png)

**Comment by smed79** [comment]
Ok, thank you.

@okiehsch fyi.
