### ISSUE TITLE
extremetech.com

### ISSUE THREAD

**Issue by terrorist96** [gorhill/uBO-Extra#102]
`https://www.extremetech.com/mobile/157528-how-can-freedompop-offer-a-completely-free-4g-data-voice-and-text-plan`

Seems like the ads slip through but then get blocked but then slip through again.

![image](https://user-images.githubusercontent.com/12802056/44486942-f556b780-a622-11e8-94f9-0e08913c7dc3.png)

![image](https://user-images.githubusercontent.com/12802056/44486953-01427980-a623-11e8-8c7e-61f8a82f619b.png)

![image](https://user-images.githubusercontent.com/12802056/44487047-41096100-a623-11e8-82a4-73ca0f06850a.png)

**Comment by mapx-** [comment]
Did you test using only uBo + uBo-extra ? (no other blocking extension)

**Comment by okiehsch** [comment]
I can't reproduce any ads even if I disable `uBO-extra`.

@terrorist96 does your logger show `g00` requests?

**Comment by terrorist96** [comment]
Hmm, I can't reproduce on my computer. I made the first post on my work computer. I'll test it again on that tomorrow.
