### ISSUE TITLE
cbssports.com

### ISSUE THREAD

**Issue by ZaphodBeebblebrox** [gorhill/uBO-Extra#106]
cbssports.com has added instart logic, and is not yet included in uBO-Extra. Example: `https://www.cbssports.com/nfl/draft/news/2019-nfl-mock-draft-no-quarterbacks-in-round-1-cowboys-add-more-speed-at-receiver/`

**Comment by okiehsch** [comment]
I have already added a [fix](https://github.com/gorhill/uBO-Extra/commit/d24c2ae2067e775ffb6270c55784b553a41c01b9), but gorhil has not yet uploaded the new version to the Chrome Web Store.
