### ISSUE TITLE
dailymail.co.uk

### ISSUE THREAD

**Issue by terrorist96** [gorhill/uBO-Extra#112]
I see ads and g00 in the logs.

`https://www.dailymail.co.uk/news/peoplesdaily/article-3847018/Is-world-s-remote-temple-Taoism-shrine-stands-5-460ft-peak-China.html`

**Comment by mapx-** [comment]
test
`dailymail.co.uk##+js(set-constant.js, Math.random, trueFunc)`

**Comment by terrorist96** [comment]
Doesn't work.

**Comment by terrorist96** [comment]
That works. Thanks.
