### ISSUE TITLE
Not working on Opera

### ISSUE THREAD

**Issue by kartana** [gorhill/uBO-Extra#114]
I could install it manually but it doesn't seem to work. Tested on ign.com. I still see the Instart Logic ads.
I have ublock origins installed too of course.

**Comment by mapx-** [comment]
try this filter in uBo
`ign.com##+js(set-constant.js, btoa, trueFunc)`

@okiehsch  now they are using `g01` and I get the crap in chrome + `uBlock Extra` (US ip)

**Comment by okiehsch** [comment]
That is not Instart Logic.

**Comment by okiehsch** [comment]
````
! https://www.reddit.com/r/uBlockOrigin/comments/9v1y40/ign_is_circumventing_adblockers/
ign.com##+js(abort-on-property-read.js, $getWin)
ign.com##^script:has-text(iframeTestTimeMS)
````
those filters were added to `uBO-filters` because of the same issue, they still work with Firefox on my end but `ign.com##+js(abort-on-property-read.js, $getWin)` can be replaced by your filter.

**Comment by kartana** [comment]
> That is not Instart Logic.
> `ign.com##+js(set-constant.js, btoa, trueFunc)` works on my end.

That one worked!
