### ISSUE TITLE
uBO-Extra breaks snapdrop.net

### ISSUE THREAD

**Issue by denilsonsa** [gorhill/uBO-Extra#12]
How to reproduce:

1. Open https://snapdrop.net/ in Chrome with *uBlock Origin Extra* enabled.
2. Open it also in another browser (like Firefox) and/or another profile (without *uBlock Origin Extra*) and/or a mobile browser.
3. Right-click (or long-tap) to try to send a text message to another device.
4. Sending/receiving does not work if *uBlock Origin Extra* is enabled.
5. Whitelisting that site/domain (by clicking on the big "power" button on uBlock Origin) has no effect.

I suspect this is related to the WebSocket wrapper injected by the extension.

* https://snapdrop.net/
* https://github.com/RobinLinus/snapdrop

**Comment by gorhill** [comment]
I think there are other issues probably related, and I've been delaying looking at this for quite a while now. I need to address this.

Looking at [Adguard's implementation](https://github.com/AdguardTeam/AdguardBrowserExtension/blob/f5acd5683cf3cb8721d68b5f26d99f4fa5cc81b3/Extension/browser/chrome/lib/content-script/websocket.js), it's much more saner than uBO-Extra's overcomplicated wrapper, and it works all fine it appears.

From the comments in the code, Adguard's implementation is itself based on [Adblock Plus' implementation](https://github.com/adblockplus/adblockpluschrome/blob/067ed8ef1c317a8a1ea1222cde1d8a5f3a58e424/include.preload.js#L393) (originally authored by @kzar in [this commit](https://github.com/adblockplus/adblockpluschrome/commit/457a336ee55a433217c3ffe5d363e5c6980f26f4#diff-c65c7b9a7a7b1819bef1a2957f08e8ceR441)). Both code base are GPLv3, so I will just go ahead and replace uBO-Extra's overcompicated and flawed WebSocket wrapper with that the saner code snippet from ABP's/Adguard's implementation.

**Comment by gorhill** [comment]
Fixed with a7e7616100d37a120151cf24b824f25c9e9af914.

**Comment by kzar** [comment]
@gorhill I'm flattered you used the code and thanks for giving me credit however would you mind amending the commit itself to correct the author? I didn't author that commit so I feel a little uncomfortable about it being pushed in my name. (The code comment is plenty IMO.)

**Comment by gorhill** [comment]
> I didn't author that commit so I feel a little uncomfortable about it being pushed in my name. (The code comment is plenty IMO.)

Sorry about this, I should just have asked beforehand. It is really your code which I imported pretty much as is aside the style. Anyway I will respect your demand. Any hint on how to change the commit history to fix this would be appreciated.

**Comment by kzar** [comment]
Ace, thanks dude :)
