### ISSUE TITLE
Ublock Origin Oct16 2019 - Breaks FireFox Dev. Oct16 2019

### ISSUE THREAD

**Issue by Chaython** [gorhill/uBO-Extra#122]
Ublock Origin Oct16 2019 - Breaks FireFox Dev. Oct16 2019
71.0b1 (64-bit) Aurora
UBO 1.22.5.104, 1.22.5.105
No sites connect w/ UBO enabled.
Uninstalling UBO Beta, going back to 1.22.4 works once again.

**Comment by mapx-** [comment]
This is uBo-extra 
For uBo report here:
https://github.com/uBlockOrigin/uBlock-issues/issues
explaining what does mean:  "Breaks FireFox Dev."

(and close this issue)

**Comment by Chaython** [comment]
UBO is limited to contributors. But I wanted to report this bug.

**Comment by mapx-** [comment]
Did you report at the address I indicated above or at this 1 ?
https://github.com/gorhill/uBlock/issues

**Comment by gorhill** [comment]
> 71.0b1 (64-bit) Aurora

I am not aware of any version of Firefox 71.0b1. Nightly is currently 71.0a1, and beta is 70.0b9 ([see](https://ftp.mozilla.org/pub/firefox/releases/). Where do you get this Firefox version?

**Comment by gwarser** [comment]
@gorhill https://bugzilla.mozilla.org/show_bug.cgi?id=1588916 

>[reddit - /ublock_on_firefox_preventing_pages_from_loading/](https://www.reddit.com/r/uBlockOrigin/comments/d4zlfi/ublock_on_firefox_preventing_pages_from_loading/) seems to indicate that this is a more general issue with uBlock Origin.

**Comment by gwarser** [comment]
This one is 71b1 - https://www.mozilla.org/en-US/firefox/developer/
