### ISSUE TITLE
site using g00 without redirect - www.closermag.fr

### ISSUE THREAD

**Issue by Procyon-b** [gorhill/uBO-Extra#123]
Not a site I'm usually visiting, but I noticed ads appearing.

`https://www.closermag.fr/politique/la-blague-ironique-d-emmanuel-macron-sur-la-fausse-arrestation-de-xavier-dupont-1037178`

fixed by adding the following line:
`||g00.closermag.fr`

**Comment by okiehsch** [comment]
Fixed in `uAssets`. Update your `uBO-filters` list.
Despite the `g00` requests, that site does not use Instart Logic.

**Comment by Procyon-b** [comment]
Thanks

Are you sure that the 3rd filter is necessary?
`||isbnwq.com^$3p`
While testing for the right filter I also blocked this hostname. But after blocking the g00 subdomain (something you also do, differently), it wasn't useful anymore.

**Comment by okiehsch** [comment]
Strictly speaking the filter is not necessary to fix this specific issue.
The filter will fix the issue for all sites that may use the same inline-script to push ads.
Blocking tt will not cause any breakage. It's sole purpose is ad-reinsertion.
