### ISSUE TITLE
Huge memory consumption 

### ISSUE THREAD

**Issue by hbxc0re** [gorhill/uBO-Extra#124]
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36 OPR/65.0.3467.48

Steps to reproduce the problem:
1.Add extension
2.Navigate to support.com or Facebook.com
3.Go to another opened tab and wait about 20 mins but don't go back to the tab for Facebook or support.com, watch the memory usage increase exponentially. 

What is the expected behavior?
Extension makes several tabs that are not in active view to consume memory. 

What went wrong?
Possibly seeing as the extension is manipulating JS it could possibly be the way the extension is handling the requests the is causing the issue of memory consumption. Note that I've seen it consume up to 10gb. 

WebStore page: https://chrome.google.com/webstore/detail/ublock-origin-extra/pgdnlhfefecpicbbihgmbmffkjpaplco

Did this work before? N/A 

Chrome version: 78.0.3904.97  Channel: n/a
OS Version: OS X 10.14.6
Flash Version: Shockwave Flash 32.0 r0

**Comment by gorhill** [comment]
uBO-Extra is inactive for `support.com` or `firefox.com`, it can't consume memory on these sites:

![a](https://user-images.githubusercontent.com/585534/69496625-1b13e180-0ea2-11ea-9e4c-37df527fe44e.png)

You need to investigate more precisely (you use the word "possibly" many times) your issue, it's not uBO-Extra -- try investigating your other extensions. Also if you really want the case that uBO-Extra is your issue, you will need to provide actual evidence -- nowhere are you providing any evidence that uBO-Extra itself is causing memory consumption, you are just speculating it does. How exactly did you measure memory usage? Did you open the dev console and create a memory snapshot to analyze the result?

**Comment by hbxc0re** [comment]
I know it's that extension, I disabled that extension and the problem went away. I used the built in developer tools that said it was that extension cause the issue

**Comment by hbxc0re** [comment]
You also need to be logged into the support.com site and have open sessions....it also slows Facebook down to a crawl after scrolling for a couple of minutes, I disabled it and the lag on Facebook is gone.

**Comment by hbxc0re** [comment]
<img width="719" alt="Screen Shot 2019-11-22 at 1 32 55 PM" src="https://user-images.githubusercontent.com/692631/69496968-cf633700-0ea5-11ea-8e90-a2a764046315.png">

**Comment by gorhill** [comment]
> I used the built in developer tools that said it was that extension cause the issue

Please provide the evidence, cut and paste what you can, screenshots, etc. I do not have an account for `support.com` or `facebook.com`. As said, uBO-Extra's content script is not active on those site.

**Comment by hbxc0re** [comment]
I'm working on that now, give me one second.

**Comment by hbxc0re** [comment]
I'm just going to say this first, only reason I'm posting is to see where the issue is. I'm currently uncertain who to go to, I've gone to Opera and Chromium and they point me back here. I just want to see what is causing the issue, I'm really grateful for the extension and just would love to continue using it, but in all honesty ever since this last update on Opera it's been killing my system resources. 

First image is of Support.com logged in with one open session, usually I have about 6-8 sessions open so the time increases the more session I have open which never used to happen before. 
<img width="729" alt="Screen Shot 2019-11-24 at 10 36 57 AM" src="https://user-images.githubusercontent.com/692631/69497115-5369ee80-0ea7-11ea-8be7-df0dcb03ce63.png">

Second image is of Facebook.com......
<img width="743" alt="Screen Shot 2019-11-24 at 10 40 43 AM" src="https://user-images.githubusercontent.com/692631/69497118-6086dd80-0ea7-11ea-999f-41ad8541b743.png">

**Comment by hbxc0re** [comment]
<img width="749" alt="Screen Shot 2019-11-24 at 10 47 17 AM" src="https://user-images.githubusercontent.com/692631/69497155-d12dfa00-0ea7-11ea-9bb3-330c6ee787ab.png">

**Comment by gorhill** [comment]
It looks to me you are using Violent Monkey and some user scripts in it. Bad user scripts are your best bet to find the culprit for your memory issue.

**Comment by hbxc0re** [comment]
Ok, I'll have to look and see whats enabled, I'll disable them and see if I can retest. Thanks for the help.
