### ISSUE TITLE
uBO-Extra failing to install in Firefox Dev 80.0b8 64

### ISSUE THREAD

**Issue by Terafugia** [gorhill/uBO-Extra#126]
Add-on fails to install (uBO-Extra-2.88) in Firefox. Firefox reports that the extension failed because it appears to be corrupt. I tried re-downloading several times, tried downloading with different browsers and installing from various different folders. Just noticed that this extension is quite old, has it been abandoned/no-longer works?

**Comment by gorhill** [comment]
Front page of the project:

> The extension is useful only for Chromium-based browsers
