### ISSUE TITLE
Rare problem with the new WebSocket wrapper code

### ISSUE THREAD

**Issue by okiehsch** [gorhill/uBO-Extra#14]
1. Use uBO-Extra 2.2
2. Add `*$websocket,domain=the-voice-of-germany.de` to your filter list.
3. Go to `http://www.the-voice-of-germany.de/tv/the-voice-of-germany/playlists/ganze-folgen`
This site uses websockets to push video ads. You may need a german IP to reproduce...
4. This results in the video being blocked because you use an adblocker.
![german](https://cloud.githubusercontent.com/assets/16838044/21442936/7d5b14ca-c8a1-11e6-94d6-c4d46da82962.JPG)
5. Use uBO-Extra 2.1
6. This results in the video playing fine and without any video ads.

Edit:
7. Disable  uBO-Extra
8. This results in the video being blocked because you use an adblocker.

Notes:
- Browser/version: Chrome 55, flash disabled, default  uBlock settings.

Video ads being pushed through websockets happens on quite a few german websites,
for example `http://www.moviepilot.de/movies/wild--3/trailer`
That site works fine with the new wrapper, hence the title
**Rare** problem

**Comment by gorhill** [comment]
Does this still occur with 2.9? I can't reproduce (using a .de VPN).

**Comment by okiehsch** [comment]
I can still reproduce and it still works with 2.1.
As a workaround I can use
` ||vod-akamai-psd2-dcp.p7s1digital.de$media,domain=example.com`
so it really is not an important issue.

**Comment by okiehsch** [comment]
With the release of Chrome 58 this issue can be closed.
