### ISSUE TITLE
uBlock Origin Extra kills websockets on meet.google.com

### ISSUE THREAD

**Issue by danielktaylor** [gorhill/uBO-Extra#16]
Google is migrating Hangouts to meet.google.com, and it is broken if uBlock Origin Extra is installed. I believe this is the exact same issue as #15 - I'm seeing the websockets get closed and the only way to fix it is to disable uBlock Origin Extra. Disabling adblocking on the site does not work.

Is it possible to add meet.google.com to the [exception list](https://github.com/gorhill/uBO-Extra/commit/ffe124d05768e24cea39cfed5cec4bcbb527c326#diff-d31e4b20da6f646d8da1878b042757f2R424)?

I'm happy to create a pull request, or do any other debugging as needed.

**Comment by gorhill** [comment]
Can you confirm it works if `meet.google.com` is added to the exception list? If it works, a pull request would be appreciated.
