### ISSUE TITLE
Breaks ShareLatex.com. Would be nice to have a whitelist

### ISSUE THREAD

**Issue by cjmalloy** [gorhill/uBO-Extra#18]

**Comment by gorhill** [comment]
What _exactly_ is broken?

**Comment by cjmalloy** [comment]
Well essentially it blocks websockets.

To repro just open any project and it will constantly say "lost connection..."

**Comment by gorhill** [comment]
> open any project

I know nothing about that site, and what a "project" is. You have a specific URL? Does one need to register?

**Comment by cjmalloy** [comment]
Yeah you need to register. It's a free site when you just have it for personal use. Essentially you can write latex in a google-docs sort of way.

**Comment by Atavic** [comment]
LaTeX documents are plain documents with a .tex extension that are meant to format the document with the help of a compiler. The compilers are on their servers:

> We’ve done a lot of work to make your compiles run as quickly as possible on our server.

**Comment by gorhill** [comment]
Maybe this was fixed when #33 got fixed?

**Comment by Atavic** [comment]
The domain has been seen to resolve to the following Hostnames:
`*.members.linode.com`

> For now, we recommend disabling 'Application Protocol Content Filtering’ in advanced settings of ESET. Disabling ESET for www.sharelatex.com is not enough.

https://www.sharelatex.com/learn/Kb/Connection_problems

The web front end: https://github.com/sharelatex/web-sharelatex
