### ISSUE TITLE
Not blocked websockets (worker)

### ISSUE THREAD

**Issue by dimisa-RUAdList** [gorhill/uBO-Extra#19]
Google Chrome 55.0.2883.87 m (64-bit)
uBlock Origin 1.10.4
uBlock Origin Extra 2.8
uBlock filters‎
EasyList
RU AdList

http://pesnik.su/
It occurs very often. This method is used advertising network Mixadvert.
They loaded the script in a worker with a domain.
`conn = new WebSocket("ws://n1.mixadvert.com:3000/1745"); conn.onmessage = function (evt) { postMessage(evt.data); conn.close();}`

**Comment by gorhill** [comment]
The fix must be made in uBO: it's a matter of injecting the websocket-blocking content security policy into the headers for javascript resources. Javascript resources used for worker purpose must be seen as root document and as such they must also be a target of filters such as `*$websocket`.

**Comment by uBlock-user** [comment]
websockets not blocked here either - http://zfilm-hd.net/ 

Ads are fetched - https://i.gyazo.com/910254cc6789b69ff70f252770113b3b.png

**Comment by gorhill** [comment]
That is not a uBO-Extra issue, that's a plain filter issue: `*$websocket,domain=zfilm-hd.net`. Report to RU Adlist.

**Comment by dimisa-RUAdList** [comment]
Such a filter (*$websocket,domain=zfilm-hd.net) in RU AdList already registered and for a long time. The problem - the same as on pesnik.su

To do so: https://hg.adblockplus.org/ruadlist/rev/b67319e220b9#l1.12

**Comment by gorhill** [comment]
> The problem - the same as on pesnik.su

Ok I see.

@uBlock-user Sorry I was confused and forgot the context of the thread and the fix to uBO, I tried `*$websocket,domain=zfilm-hd.net` and did not get the ads -- so at least this confirms [the fix](https://github.com/gorhill/uBlock/commit/54032e520b4259f010517e55381cdaa286d2d1c0) works.

**Comment by uBlock-user** [comment]
@gorhill No worries and thanks for the quick fix as always.

**Comment by dimisa-RUAdList** [comment]
By the way, the fix will be useful not only for Google Chrome, but and for Firefox.

**Comment by gorhill** [comment]
@dimisa-RUAdList I can't reproduce the case in the opening comment. Do you know of another such case where workers are used to bypass blockers?

**Comment by dimisa-RUAdList** [comment]
I have not seen this for a long time. At the moment, the extension code is enough to handle the rules from the subscription RU AdList (+EasyList). Including in Firefox.
