### ISSUE TITLE
Firefox version please

### ISSUE THREAD

**Issue by Dimas-sc** [gorhill/uBO-Extra#20]
Using the new WebExtensions should be easy to port it to Firefox

**Comment by IDKwhattoputhere** [comment]
[Use search.](https://github.com/gorhill/uBO-Extra/search?q=firefox&type=Issues&utf8=%E2%9C%93)

**Comment by gorhill** [comment]
If you experienced any one of the issueswhich is meant to be addressed by this extension while using Firefox, please open a **detailed** issue. So far, all the issues listed occurs only when using a Chromium-based browser.
