### ISSUE TITLE
ublock extra release for opera store

### ISSUE THREAD

**Issue by peterxiyong** [gorhill/uBO-Extra#27]
there is no release of ublock extra in opera store officially....
iam loading extension locally in developer mode
please release in opera store officially

**Comment by gorhill** [comment]
Just download and manual-install from [releases](https://github.com/gorhill/uBO-Extra/releases).

**Comment by domnar** [comment]
hello, 
first: thank you for this great extension!
i try to install this extension in Opera latest (Win) via the "Load unpacked extension", which works, but it never gets added to the extension folder and restarting the browser will cause the extension to get lost. Any option there to directly install it into the extension directory to make it stick? Would prefer not to use the GOOGLE extension helper extension...

**Comment by gorhill** [comment]
Use <https://addons.opera.com/en/extensions/details/install-chrome-extensions/> to install extensions from the Chrome store.
