### ISSUE TITLE
onet.pl detects adblock

### ISSUE THREAD

**Issue by F4z** [gorhill/uBO-Extra#28]
uBlock Origin 1.11.0
uBlock Origin Extra 2.9
Google Chrome 56.0.2924.87

I noticed that if I have enabled uBO + uBO Extra, then this website - `http://www.onet.pl/` - detects "adblock", but without uBO Extra it works "properly".

To reproduce.
1. Disable all filter list
2. Add these two rules to my filters
`||csr.onet.pl^`
`||gemius.pl^`
3. Go here - `http://www.onet.pl/`
4. You will see that website is asking to disable adblock<details><summary>Screenshot</summary>
![image](https://cloud.githubusercontent.com/assets/11742596/22954934/a10220f6-f319-11e6-9677-e64342e67dd7.png)</details>
5. Disable uBO Extra and reload website
6. No message to disable adblock

To resolve this problem I can also add these rules:
`@@||onet.hit.gemius.pl/fpdata.js?href=www.onet.pl$script`
`@@||onet.hit.gemius.pl/xgemius.js$script`
to my filters and it will work properly, but I wonder why these rules are needed, if  without uBO Extra, I do not need them.

**Comment by gorhill** [comment]
The site is using the `name` property to find out whether the WebSocket constructor has been wrapped.

**Comment by F4z** [comment]
It works, thank you for fix and answer.

**Comment by PrzemyslawKlys** [comment]
It seems the issue is back. Using 2.11. As soon as i disable it onet.pl works fine.

**Comment by Matthaiks** [comment]
It's still broken.

**Comment by gorhill** [comment]
I see the site asking to disable the blocker without uBO-Extra, so that's not a uBO-Extra issue.

**Comment by F4z** [comment]
I also can reproduce a problem again.
Steps to reproduce in my first post.

I think, that they added something with `RTCPeerConnection` to their script, because I did not remember that it was before, but I might be wrong.
```
G = function(a) {
    try {
        if ("WebSocket" !== a.WebSocket.name || a.Object.getOwnPropertyDescriptor(a.Element.prototype, "shadowRoot").get.toString().indexOf("[native code]") < 0 || 0 === a.RTCPeerConnection.name.indexOf("bound") || 0 === a.webkitRTCPeerConnection.name.indexOf("bound")) return !0
    } catch (a) {}
    return !1
}
```

**Comment by Rageofhonor** [comment]
I don’t know what onet.pl is doing but they can find out that I use an ad blocking software and they make the text disappear. Instead of the text I get gray blocks. How t solve this?

**Comment by gorhill** [comment]
For no try [toggling off cosmetic filtering](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering).
