### ISSUE TITLE
Beam.pro chat interferance

### ISSUE THREAD

**Issue by snook** [gorhill/uBO-Extra#29]
This interferes with http://beam.pro chat, for example https://beam.pro/Monstercat

Direct link to chat https://beam.pro/embed/chat/Monstercat

Unsure if it's Beam that needs to fix this or if it's the extension so I'm reporting it to both.

**Comment by gorhill** [comment]
The site's favicon returns 404: <https://beam.pro/_latest/assets/icons/favicons/favicon-16x16.png>.

I need to convert both uBO and uBO-Extra to use XMLHttpRequest instead of an image, this way uBO-Extra can use the response headers to find whether the request was cancelled or not by an extension.

**Comment by gorhill** [comment]
For now I will push a quick fix with minimal changes.
