### ISSUE TITLE
Info : Websocket interception available in Chrome 58.

### ISSUE THREAD

**Issue by Betsy25** [gorhill/uBO-Extra#32]
[Link](https://bugs.chromium.org/p/chromium/issues/detail?id=129353#c87)

**Comment by uBlock-user** [comment]
Yes, its finally works.

Test-case - https://websocketstest.com/

Disable uBO-Extra from the extensions page, open logger and refresh, you will notice `websocket` being listed.

FYI - You need version `58.0.3021.0` or higher.
