### ISSUE TITLE
uBO Extra blocks websdr sites

### ISSUE THREAD

**Issue by rextheleopard** [gorhill/uBO-Extra#33]
- Windows x64 10.0.15048
- Chromium 59.0.3030.0 x64 <a href="https://github.com/henrypp/chromium/releases/tag/v59.0.3030.0-r454662-win64">Nik build</a>
- uBO 1.11.3.1 from github
- uBO Extra 2.11 from google webstore
- web-sdr based site http://95.165.168.126/

uBO Extra blocks audio feed from websdr-based sites <a href="http://95.165.168.126/">this</a> for example.

1. Enable uBO and uBO extra
2. Open websdr-based site
3. bug: there is no sound from webpage (error from chromium engine: failed: WebSocket is closed before the connection is established)
4. Go to extensions page and disable uBO extra, uBO still on
5. Websdr-based sites works ok

If uBO disabled but uBO extra enabled, websdr sites still does't work at all. I think it's not a filter list problem because uBO can be disabled.

**Comment by gorhill** [comment]
I can't reproduce. You have any custom rules in uBO? What filter lists are selected? Any other blocker?

**Comment by rextheleopard** [comment]
I disable all other extensions and uBO too, websdr sites doesn't fork. uBO extra communicate with uBO filters even if uBO not loaded?

**Comment by gorhill** [comment]
See what is blocked on that page with uBO's logger. Here is what I get:

![a](https://cloud.githubusercontent.com/assets/585534/23795754/2f9aa434-0565-11e7-9a76-91dca18c827f.png)

**Comment by gorhill** [comment]
Well a difference is that I am testing with Chromium 56 (linux), I won't install someone's personal built, and I do not have Windows anyways.

**Comment by rextheleopard** [comment]
Nothing strange

![ubo](https://cloud.githubusercontent.com/assets/26321641/23795945/9d6b634e-05b1-11e7-874b-1cc63f86f313.png)

**Comment by gorhill** [comment]
Ok I get it. uBO-Extra needs to be updated to account for teh fact that Chromium 58+ support natively websocket blocking. I need to modify uBO-Extra to disable websocket wrapper for Chromium 58+.

**Comment by rextheleopard** [comment]
OK, thanks!
