### ISSUE TITLE
[QUESTION] Why no uBO-Extra in ChrOpera's (Opera on Chromium) add-ons store?

### ISSUE THREAD

**Issue by Piter432** [gorhill/uBO-Extra#36]
I know that is possible to install uBO-Extra for ChrOpera (Opera on Chromium) by using Developer mode in ChrOpera's extension page and .zip file from Release page, but I wonder, why the uBO-Extra don't exist in the ChrOpera's add-ons store. Is Opera Software doesn't allow you to upload it there or what? If you don't want to explain why, just write me here, please.

**Comment by gorhill** [comment]
Because I don't have time. It can easily be installed from the Release section.

**Comment by Piter432** [comment]
Okay, thanks for your answer 😃
