### ISSUE TITLE
Don't know how to install on Firefox

### ISSUE THREAD

**Issue by Uricorn** [gorhill/uBO-Extra#38]
I am trying to install this on Firefox.

I downloaded the latest release as instructed by the README but when I got to about:addons and then to the 'Extensions' tab, there is no way to 'check "Developer mode"' so that I can upload an unpacked extension.

I am not sure if that is supposed to be found in a different place, or if it is no longer a feature in Firefox, so I would appreciate if you could elaborate more on how to do that.

If I manage to install this, I can make a pull request with a more visual README so that the less tech savvy user can complete the installation with ease.

**Comment by gorhill** [comment]
The extension is useful only for Chromium-based browsers, there is no need for it on Firefox (so far).

I update the front page of the project to mention this.

**Comment by ghostwords** [comment]
@gorhill, Could you also update the status of this extension, now that WebSocket interception has been implemented by Chrome? ([Previous request for clarification.](https://github.com/gorhill/uBO-Extra/issues/37#issuecomment-289631236))

**Comment by gorhill** [comment]
This is the status: <https://github.com/gorhill/uBO-Extra/wiki/Sites-on-which-uBO-Extra-is-useful>.
