### ISSUE TITLE
speedtest.net stuck at Finding optimal server

### ISSUE THREAD

**Issue by randomish** [gorhill/uBO-Extra#39]
This is with the new speedtest which was in beta until recently, but seems to be the default now. I believe it uses html5 and not Flash like the old version.

http://www.speedtest.net/

With uBO-Extra enabled I can't seem to get past the "Finding optimal server" stage, which is the first thing that happens before/when running a normal speedtest.

Disable uBO-Extra and the speedtest completes normally.

OS: Win10 x64
Tested browser 1: Vivaldi 1.8.770.46 (64-bit) (Chrome/57.0.2987.111)
Tested browser 2: Chrome 57.0.2987.133 (64-bit)

**Comment by gorhill** [comment]
The issue is the filter `|http://$xmlhttprequest,domain=speedtest.net` in EasyList, it prevents uBO-Extra from doing its job.

**Comment by uBlock-user** [comment]
Works fine here, the filter must have been removed, force update your filters and try again.

**Comment by gorhill** [comment]
I still can reproduce. Does this work?

    |http://$xmlhttprequest,domain=speedtest.net,badfilter
