### ISSUE TITLE
uBO-extra breaks twilio-video.js sdk's webrtc on localhost

### ISSUE THREAD

**Issue by jskrzypek** [gorhill/uBO-Extra#41]
uBO-extra's wrapper around RTCPeerConnection is breaking my ability to develop with Twilio's twilio-video javascript sdk (https://github.com/twilio/twilio-video.js). I lost like 4 days of dev time confused as to why this was broken before I realized that uBO-extra was wrapping RTCPeerConnection

If you want to reproduce this you can use their quickstart node app: https://github.com/TwilioDevEd/video-quickstart-node

With uBO-extra enabled you get this error, but it disappears when the extension is disabled.

>`this._peerConnection.addStream is not a function1`
    `at PeerConnectionV2.addMediaStream (`[`twilio-video.js:4052`](https://github.com/twilio/twilio-video.js/blob/1.0.0-beta5/dist/twilio-video.js#L4052)`)`
    `at PeerConnectionManager._getOrCreate (`[`twilio-video.js:4309`](https://github.com/twilio/twilio-video.js/blob/1.0.0-beta5/dist/twilio-video.js#L4309)`)`
    `at getConfigurationSucceeded (`[`twilio-video.js:4338`](https://github.com/twilio/twilio-video.js/blob/1.0.0-beta5/dist/twilio-video.js#L4338)`)`

It would be nice to be able to add domains to the exception lists without needing an actual source code change.

**Comment by gorhill** [comment]
What is the browser version?

> It would be nice to be able to add domains to the exception lists without needing an actual source code change.

Not possible. If it was possible, wrapping in this extension would not be required, it could be done uBO-side. There is already a filter on uBO side to filter out WebRTC connection, it does not work if a web page uses RCPeerConnection before uBO can wrap it. uBO-Extra wraps unconditionally before any script on the page has run, this is why it can filter out WebRTC connections on some sites whereas it's not possible with filter-based uBO.

**Comment by gorhill** [comment]
Did you look at uBO's logger to see if there were filters potentially causing this?

**Comment by jskrzypek** [comment]
I'm on Chrome 58.0.3029.54 (beta).

I have localhost whitelisted in uBO so no uBO-side filters ought be affecting it.

I cloned uBO-Extra locally and added `'localhost'` to the domains in the exceptions list here: https://github.com/gorhill/uBO-Extra/blob/master/contentscript.js#L544-L548, then installed my local clone of the repo as an extension.

With the edited version, my app on localhost does not have the issue, but with the chrome web store version I do have the errors.

**Comment by jskrzypek** [comment]
So looking again at the scriptlet I noticed that you're only including 3 methods in the wrapped RTCPeerConnection's prototype. Is there a reason you don't carry over everything? Also testing with my local dev version of the extension, I found that something like this will also fix the issue:
```
    bound.prototype = {};
        for (var propertyName of Object.getOwnPropertyNames(RealRTCPeerConnection.prototype)) {
            Object.defineProperty(bound.prototype, propertyName, Object.getOwnPropertyDescriptor(RealRTCPeerConnection.prototype, propertyName));
        }
        for (var propertySymbol of Object.getOwnPropertySymbols(RealRTCPeerConnection.prototype)) {
            Object.defineProperty(bound.prototype, propertySymbol, Object.getOwnPropertyDescriptor(RealRTCPeerConnection.prototype, propertySymbol));
        }
```

If those other methods are attack vectors, then fine, but if not I think something like this would be the most non-disruptive way to wrap the class.

**Comment by gorhill** [comment]
uBO-Extra 2.45 no longer wrapping RTCPeerConnection.
