### ISSUE TITLE
uBO-Extra enabled causes connection loops with Plex

### ISSUE THREAD

**Issue by Givemeyourgits** [gorhill/uBO-Extra#42]
When uBO-Extra is enabled, I get continuously failed connects when trying to access my media server via my Plex portal.  If I disable uBO-Extra (while uBO & Privacy Badger are still running) the problem goes away.

![image](https://cloud.githubusercontent.com/assets/1454872/24996154/c46b9a32-1fff-11e7-974c-224e666eed35.png)

Plex is a media server similar to Windows Media Center, you have the ability to create multiple servers and access them all from https://app.plex.tv which securely redirects to your local server.  Somewhere in this process, uBO-Extra is tripping.  I do not see any blocks in the uBO log files.  As of right now, the only solution I can find is to disable uBO-Extra if I want to continue using Chrome (I do).

**Comment by gorhill** [comment]
Unfortunately, no versions for uBO-Extra/uBO provided.

> I do not see any blocks in the uBO log files.

You mean uBO's logger I suppose? Did you select the _All_ entry at the top of the logger? The behavior you describe is as if one of the network request was blocked.

**Comment by Givemeyourgits** [comment]
uBO 1.12.0 / uBO-Extra 2.20 both running latest.

Yes, uBO logger.  Yes, I have used All and the specific tab, both show the same thing.  I don't see anything being blocked.  The behavior of Plex, when using their site rather than connecting to my servers directly, is to redirect requests to my server.  I know if you run dnsmasq (which I don't) it can foul this up, not sure if that helps determine where the problem lies.

**Comment by gorhill** [comment]
uBO makes a network request `HEAD` to the the remote server to find out whether it should block websocket connections. Example:

![a](https://cloud.githubusercontent.com/assets/585534/25006651/c6b77726-202b-11e7-9e9e-4123ca4dc19d.png)

The request wasn't blocked by an extension and thus the websocket connection was not forcibly closed.

Is there anything of interest in the Network tab?

**Comment by Givemeyourgits** [comment]
If I turn on uBO-Extra I start getting these messages:

Mixed Content: The page at 'https://app.plex.tv/web/app#!/status' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://plex.tv/'. This request has been blocked; the content must be served over HTTPS.

If I turn it off and refresh the page, I don't get any error messages and everything works.

Just a little information, I have "required secure connections" in Plex, so if it doesn't see secure connections (ssl and a few other things) it will not allow connections at all.  When uBO-Extra is turned on, it is being forced to go to http://plex.tv/ rather than https://plex.tv as a failover which ends up throwing the above error and not allowing the connection.

**Comment by gorhill** [comment]
> When uBO-Extra is turned on, it is being forced to go to http://plex.tv/ rather than https://plex.tv as a failover

uBO does not redirect web pages, I don't understand why there would be a downgrade from https to http when uBO-Extra is present. What exactly is forcing your page to fall to http?

**Comment by Givemeyourgits** [comment]
I really am not sure, I know it will try SSL but if it fails it will fall back to http.  Something is causing it to fail when uBO-Extra is turned on.  If I turn it off everything works without a problem.

Looking at debug I see this, the extension ID is uBO-Extra

![image](https://cloud.githubusercontent.com/assets/1454872/25013775/eca9b054-2042-11e7-97fa-a26868733a5a.png)

**Comment by gorhill** [comment]
If I enter `https://app.plex.tv/` in the brwoser, the Network tab shows that the request is redirected to `http://plex.tv/`, then to `https://plex.tv/`, then again to `https://www.plex.tv/`.

The one redirection to `http://plex.tv/` is what causes the original request to be aborted by the browser, and uBO-Extra sees this as the request being blocked by an extension (it was the browser itself), and thus cancels the websocket connection.

I will need to investigate if this can be fixed, and how if so.

**Comment by Givemeyourgits** [comment]
I don't see that, this is when I goto https:/app.plex.tv

![image](https://cloud.githubusercontent.com/assets/1454872/25014739/f5dae23e-2046-11e7-9a66-0c22724874d2.png)

If I go to "launch" which shows my panel, I only get "mixed content" errors when uBO-Extra is running, otherwise, it is pure HTTPS.

![image](https://cloud.githubusercontent.com/assets/1454872/25014762/10093926-2047-11e7-99c6-34485dac631d.png)

**Comment by gorhill** [comment]
> I don't see that

This is definitely the issue. You have to look into the Network pane, not what the console reports.

**Comment by Givemeyourgits** [comment]
I am using network pane.

![image](https://cloud.githubusercontent.com/assets/1454872/25015111/64561cc8-2048-11e7-9f78-f68e6220dc80.png)

**Comment by gorhill** [comment]
The console is covering your Network pane. That is the Network pane, and the evidence that `https://app.plex.tv/` is redirected by the server to `http://plex.tv/`:

![a](https://cloud.githubusercontent.com/assets/585534/25015441/d3697cc6-2049-11e7-86b8-fbe7d518d3d6.png)

**Comment by gorhill** [comment]
I had to create an exception to fix this, I couldn't find any other way. Just to be sure, would you mind testing [v2.21 in Releases](https://github.com/gorhill/uBO-Extra/releases/tag/2.21) by installing the extension manually?

**Comment by Givemeyourgits** [comment]
I see what you mean about console now and confirm I see the same thing now.

The beta version works like a champ, thank you for responding so fast!
