### ISSUE TITLE
.

### ISSUE THREAD

**Issue by PekaFat** [gorhill/uBO-Extra#45]

**Comment by PekaFat** [comment]
Update:
When I block this:
`||volantix.com/index.js`
`||volantix.com/check.js`
All has become fine.

**Comment by gorhill** [comment]
It's fine on my side now without blocking this -- maybe it was a temporary server issue?

**Comment by gorhill** [comment]
https://github.com/uBlockOrigin/uAssets/commit/13dc0c32a16f2d6b397f5c72de9e0371ca45b4e1

**Comment by PekaFat** [comment]
> maybe it was a temporary server issue?

Maybe :)
