### ISSUE TITLE
[Suggestion] Move uBO-E functionality to uBO

### ISSUE THREAD

**Issue by uboeuser** [gorhill/uBO-Extra#46]
Hello, if Chrome can block WS start from 58 ver. maybe it's time to move uBO-E functionality to uBO? For users to have one extension less.

**Comment by gorhill** [comment]
Read [release notes](https://github.com/gorhill/uBlock/releases/tag/1.12.0) please.

**Comment by uboeuser** [comment]
Which part of notes? I know that uBO already can block WS, but uBO can't block Instart Logic crap.
