### ISSUE TITLE
Google G Suite Admin Console

### ISSUE THREAD

**Issue by dadanox** [gorhill/uBO-Extra#49]
Ublock origin Extra blocking GSuite Admin at admin.google.com .  Turn off by site like regular ublock Origin would be good.

**Comment by gorhill** [comment]
> Turn off by site like regular ublock Origin would be good.

Turn off by site would cause the extension to stop working properly.

Now if you can find what exactly is breaking the site, I will add it as an exception.

**Comment by gorhill** [comment]
Issue probably obsolete now..
