### ISSUE TITLE
[suggestion] regarding document.write blocking in Chrome

### ISSUE THREAD

**Issue by eladkarako** [gorhill/uBO-Extra#50]
fyi
Chrome will blocks <code>document.write</code>,
100% of the scripts written with <code>document.write</code> won't be executed (by design).
Also, a user can switch extended blocking to all <code>document.write</code> executions, through <code>chrome://flags</code>. This is related to both extensions and web-pages (included native web-pages source and source modified by context-script).

The workaround (which is actually the proper solution as well..) is the only use <code>document.write</code> to write the DOCTYPE, since it won't work otherwise (when put innerHTML)-- and assign the rest of the HTML source into <code>document.documentElement.innerHTML</code>.

If you're getting inconsistent results with your extension, on different browsers, this is why.

Saw your code uses it, and just thought it might help. Solved it for few of my extensions (for example <a href="https://github.com/eladkarako/Chrome-Extension-Meta-Refresh-Killer/"><em>this one</em></a> which also stops early parsing to make it more efficient..)

**Comment by gorhill** [comment]
Using `innerHTML` does cause the script tags in it to be executed, unlike `document.write`. It's not an issue in your extension because all script tags have already been executed, and you are not trying to prevent them from executing.
