### ISSUE TITLE
Breaks appear.in service

### ISSUE THREAD

**Issue by mishtershmart** [gorhill/uBO-Extra#52]
Howdy,

Been using uBlock origin + extra for a while now and, only recently, did I start having issues using https://appear.in (video chat). I've narrowed this down to the uBlock Extra extension, which I currently have disabled. 

I have appear.in whitelisted as well as signal.appear.in and api.appear.in, but still can't get it working with the Extra extension enabled. 

If someone can take a look at this and either fix an issue (if there is one) or give me some advice on how to allow the service to work, that'd be great. 

Cheers,
Phil

**Comment by gorhill** [comment]
Does uBO's logger report any blocked websocket connections?

**Comment by mishtershmart** [comment]
I presume they're only blocked if they are red in the log? If so, there none blocked. There are a few wss:// entries but nothing highlighted.

**Comment by gorhill** [comment]
Any error at the browser console? Also, which version of Chromium are you using?
