### ISSUE TITLE
pcmag.com breaks with uBO-extra

### ISSUE THREAD

**Issue by BillyJoeJimBob** [gorhill/uBO-Extra#53]
browser: Chrome 60.0.3112.90
macOS 10.12.6
https://www.pcmag.com/   breaks and goes into a constant reloading loop if uBO-Extra is enabled.  disabling uBO-Extra allows the site to load properly even with the main uBO extension enabled.  This happens with all other extensions disabled.  Is there a way to whitelist this site in uBO-Extra?  Thank you.

**Comment by gorhill** [comment]
I can't reproduce issue with uBO-Extra 2.31 + uBO 1.13.8 + default settings/lists, tried on Chromium 59 and Chrome 61.

**Comment by gorhill** [comment]
See if this help: clear all cookies for the site.

**Comment by jspenguin2017** [comment]
I can reproduce it, it only affect the home page. It's not quite a reload loop, but the home page stay blank. Individual articles inside still works. 
![image](https://user-images.githubusercontent.com/7283682/29003822-2a6b2282-7a7b-11e7-897f-b69668aade9a.png)

**Comment by gorhill** [comment]
Since I can't reproduce, I can't verify whether moving `pcmag.com` from IL buster v1 defuser to IL buster v3 work... Are you willing to try?

**Comment by jspenguin2017** [comment]
Yes, that does work.

**Comment by gorhill** [comment]
Thanks for helping, I will fix this way.
