### ISSUE TITLE
wikia.com

### ISSUE THREAD

**Issue by okiehsch** [gorhill/uBO-Extra#54]
`wikia.com` now also uses `Instart Logic`
Example link: `http://thewire.wikia.com/wiki/The_Wire_on_HBO`
Adding `wikia.com` to IL buster v1 works on my end without any obvious site breakage.
IL buster v3 also works and can be used should somebody complain about site breakage using one 
of the thousands of wikia-subsites.

**Comment by gorhill** [comment]
I think I will go with v3 given the amount of subdomain `wikia.com`, v1 tends to mess with other extensions with content scripts.
