### ISSUE TITLE
[Question] In Chromium browsers, how does uBlock Origin Extra relate to uMatrix?

### ISSUE THREAD

**Issue by milopiccolo** [gorhill/uBO-Extra#55]
Hi,

I've been trawling through the documentation but I can't find the answer to what must be a common question.

If I want to block WebSockets on Chromium browsers, will I be fine with uMatrix, or do I need to install uBlock Origin Extra, or do I need to abandon uMatrix and use uBlock Origin + uBlock Origin Extra?

**Comment by gorhill** [comment]
Yes, uMatrix can block websocket requests, these appear in the `XHR` columns.

(Why not just open uMatrix's logger and try using a [websocket demo](https://html5demos.com/web-socket/) to find out?)
