### ISSUE TITLE
It breaks sites listed as being handled by this extension 

### ISSUE THREAD

**Issue by strah** [gorhill/uBO-Extra#57]
On many sites from the list here:  
https://github.com/gorhill/uBO-Extra/wiki/Sites-on-which-uBO-Extra-is-useful  
there is a console error:

```
VM158:12 Uncaught TypeError: Cannot read property 'querySelectorAll' of undefined
    at XMLHttpRequest.req.onload (<anonymous>:12:28)
req.onload @ VM158:12
XMLHttpRequest.send (async)
(anonymous) @ VM109:1
(anonymous) @ VM158:25
(anonymous) @ VM158:26
(anonymous) @ contentscript.js:730
(anonymous) @ contentscript.js:733
```
and blank page is shown.

I tested it on:
baltimoresun.com
boston.com
dailypress.com
geek.com
gofugyourself.com

**Comment by gorhill** [comment]
I moved `baltimoresun.com`, `boston.com` and `dailypress.com` to IL defuser v4.

I removed `geek.com` and `gofugyourself.com`, from my side they do not seem to use IL tech anymore.

That would be nice if others can confirm my findings.

**Comment by gorhill** [comment]
https://github.com/gorhill/uBO-Extra/releases/tag/2.36

**Comment by okiehsch** [comment]
1. I do not see any site breakage at `baltimoresun.com`, `boston.com` and `dailypress.com` using
IL defuser v1 or v4.
2. `geek.com`does not use IL tech on my end.
3. `gofugyourself.com` still uses IL tech on my end.
![sn](https://user-images.githubusercontent.com/16838044/29280847-170c4164-811d-11e7-86a8-a514b3c8bf86.PNG)

**Comment by gorhill** [comment]
Ok I could reproduce with `gofugyourself.com`, I used uMatrix to force a UA for Chrome 59/Windows, can't tell whether this is triggered IL to come back, it seems a bit random.

I re-created 2.36 with `gofugyourself.com` added to ILv4.
