### ISSUE TITLE
uBO-Extra breaks Allo for Web

### ISSUE THREAD

**Issue by xdreamwalker** [gorhill/uBO-Extra#59]
I have no idea regarding the how/what this is happening, however Google just released the Allo for Web client, https://allo.google.com/web and it will not function properly with uBO-Extra enabled. As soon as uBO-Extra is turned off it loads correctly.

**Comment by gorhill** [comment]
Would you mind testing 2.38 from [Releases section](https://github.com/gorhill/uBO-Extra/releases/tag/2.38) with a manual install? I am not in a position to test this -- just assuming that I need to whitelist `google.com` instances of WebRTC use.

**Comment by xdreamwalker** [comment]
Yeah, that fixed it. I see that you had a whitelist entry for hangouts and meet, but just did it for all of google.com. That did the trick.
