### ISSUE TITLE
Qualys Client test shows Websocket failing (again) for mixed content

### ISSUE THREAD

**Issue by TheRyuu** [gorhill/uBO-Extra#6]
This was broken to begin with then fixed but now it appears to be broken again[1] with the (fairly) recent changes to the uBO-WebSocket extension.  This issue has to do with mixed content.  Expected results is for it to say "No" not "Test Failed".

After further testing it appears that this has been broken ever since this split off into its own extension.  I tried rolling back versions one by one (that had code changes) and all of them back to the first commit produced the same result of "Test Failed".

At one point this was fixed before it got split into its own extension.  It should not be affecting mixed content since such content will already be blocked by the browser.

This was originally reported here[2] but that was me having a brainfart.

[1] https://www.ssllabs.com/ssltest/viewMyClient.html
[2] https://github.com/gorhill/uBlock/issues/1887

**Comment by gorhill** [comment]
Can't reproduce:

![a](https://cloud.githubusercontent.com/assets/585534/17587342/c7c2a84a-5f95-11e6-9fca-c13d905cedca.png)

**Comment by gorhill** [comment]
Can't reproduce:

![a](https://cloud.githubusercontent.com/assets/585534/17587418/409601a4-5f96-11e6-9762-5e53ab622dfc.png)

**Comment by moraesbo** [comment]
![screenshot at 2016-11-11 11-10-36](https://cloud.githubusercontent.com/assets/23319051/20209927/a3133ab6-a7ff-11e6-9c3d-4fae553a085e.png)

**Comment by gorhill** [comment]
Because of issue #7.

**Comment by gorhill** [comment]
Can't reproduce with latest version of uBO-Extra.
