### ISSUE TITLE
sporcle.com

### ISSUE THREAD

**Issue by okiehsch** [gorhill/uBO-Extra#60]
`sporcle.com` login is broken with uBO-extra enabled, moving `sporcle.com` to
IL-defuser v4 fixes this issue on my end.

**Comment by okiehsch** [comment]
@gorhill I think you should consider moving the sites listed in IL-defuser v1 to IL-defuser v4.
I tested all sites  and could not find any breakage or g00-redirect at all.
The sites 
````
celebslam.com
celebuzz.com
gamepedia.com
idigitaltimes.com
thefrisky.com
thesuperficial.com
tmn.today
````
have no remnant of IL-code on my end.

**Comment by gorhill** [comment]
Looks like I missed the notification for this issue when it was filed.

I was actually [considering doing so just today](https://www.reddit.com/r/uBlockOrigin/comments/6npiot/report_metacritic_is_using_instart_logic_crap/dlrnjy8/). Many thanks for having gone through testing all this.

**Comment by gorhill** [comment]
I just added you as collaborator, so that you can commit yourself the fix for which you work.

**Comment by okiehsch** [comment]
Just for clarification I tested all sites listed IL-defuser v1, I did not tes the sites in IL-defuser v2 and v3.
If you want I can test them too in the next few days.
