### ISSUE TITLE
legacy.com

### ISSUE THREAD

**Issue by gotitbro** [gorhill/uBO-Extra#64]
g00 ads on http://www.legacy.com.

**SS:**
https://i.imgur.com/8wHyvDE.png (SS of webpage showing the ads)
https://i.imgur.com/7JlY10z.png (Logger showing g00 requests)
https://i.imgur.com/7oFyGd3.png (Logger showing whitelist filters in EasyList)

**Error URL:**
`http://www.legacy.com/obituaries/vancouversun/obituary-search.aspx?daterange=30&keyword=maria&countryid=2&stateid=6&affiliateid=all`

@gorhill I believe you want this repository to be the place for g00 related issues. I am opening this issue here for this reason.

There are here gain many whitelist filters in EasyList which do not help. Any solution to counter these whitelist filters?

_**Note:** Using uBO 1.13.8 with the default filters and settings and uBO-Extra._

**Comment by uBlock-user** [comment]
> Any solution to counter these whitelist filters?

`$badfilter` them all or block them via `$important`
