### ISSUE TITLE
trustedreviews.com ign.com

### ISSUE THREAD

**Issue by jjohns71** [gorhill/uBO-Extra#65]
Hi,

Two more IL infected sites to report.

www.ign.com - seems IL only sometimes fires on this after you navigate to an article but seems to always fire off when just navigating to the home page (www.ign.com).

www.trustedreviews.com - [example article](http://www.trustedreviews.com/news/when-next-steam-sale-time-date-summer-christmas-deals-2936875)

Thanks

**Comment by uBlock-user** [comment]
@okiehsch Found another one - https://www.space.com/38372-nanoracks-funding-commercial-airlock-module.html

**Comment by mlsad3** [comment]
Can you please add slickdeals.net to this?
Example: https://slickdeals.net/f/11142163-deus-ex-mankind-divided-season-pass-ps4-digital-download-4-49-deus-ex-mankind-divided-is-still-free-for-ps-members

**Comment by gorhill** [comment]
Can you confirm this works?

**Comment by mlsad3** [comment]
Good question. Let me check out your repo and try

**Comment by mlsad3** [comment]
Hey it's beautiful again! I can see images on the site! Thanks for the fix!
