### ISSUE TITLE
instart logic few more sites

### ISSUE THREAD

**Issue by peterxiyong** [gorhill/uBO-Extra#66]
i think instart logic last ***updated 1 sep 2017***
@gorhill and @okiehsch , can you test it out below mentioned sites for g00/instart logic ads
 afterellen.com
 cattime.com
 craveonline.com
 dayzdb.com
 dotaoutpost.com
 esohead.com
 everquest.allakhazam.com
 momtastic.com
 musicfeeds.com.au
 mustangandfords.com
 realitytea.com
 superherohype.com
 thefashionspot.com
 totalbeauty.com

***using ublock origin default settings with uptodate filters and ubo extra 2.48 on chrome***

**Comment by okiehsch** [comment]
@gorhill all mentioned sites use IL and all are fixed without any obvious breakage on my end, if added to uBO-extra.

**Comment by gorhill** [comment]
Thanks for taking the time to test all this.

Can you commit the changes? I will be able to upload to the store tomorrow morning.
