### ISSUE TITLE
Instart on wowhead

### ISSUE THREAD

**Issue by johnsolver** [gorhill/uBO-Extra#75]
Looks like they changed something, uBO-Extra no longer disables it.

Chromium, latest versions of uBO and uBOe

**Comment by okiehsch** [comment]
Yes, I get redirected on quite a few sites, `chicagotribune.com` or `capitalgazette.com` for example.

**Comment by johnsolver** [comment]
Weird voodoo, looks like version `Thu Nov 16 2017 - version: 8.3.21` is being diffused.

**Comment by okiehsch** [comment]
`version: 8.3.20` was probably buggy so they had to patch it.

**Comment by gorhill** [comment]
Does the fix work for you?

**Comment by okiehsch** [comment]
Yes, works fine on my end. 👍
