### ISSUE TITLE
Ads Loading

### ISSUE THREAD

**Issue by Gorthezar** [gorhill/uBO-Extra#76]
Ads on the video players on Fox are loading.
Example https://www.fox.com/watch/4e9ac96523b454de771f95a4f775facb/

**Comment by uBlock-user** [comment]
That's not INSTART, but rather Server Sided Ad Insertion made by Verizon.

**Comment by terrorist96** [comment]
See https://github.com/uBlockOrigin/uAssets/issues/1905. This should be closed.
