### ISSUE TITLE
What is now with Firefox?

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uBO-Extra#78]
@gorhill 
First, my wish is NOT to make trouble here or even stress, nevertheless:

As you said in #https://github.com/uBlockOrigin/uAssets/issues/227 it's possible to have the undesired IL in Firefox too. How is the situation now?

Or can this handled with the new HTML filtering possibility with webext in Fx 57+?

I feel a bit confused or even unsecure at the moment ...

**Comment by uBlock-user** [comment]
Yes he did say that for FF.

**Comment by Alpengreis** [comment]
@uBlock-user 

You mean he said that it's possible in Fx too OR can handled with HTML filtering?

Thank you!

**Comment by uBlock-user** [comment]
HTML Filtering can handle it.

**Comment by Alpengreis** [comment]
Ahh ok, that's really good then, thank you @uBlock-user!
