### ISSUE TITLE
ign.com

### ISSUE THREAD

**Issue by pishposhmcgee** [gorhill/uBO-Extra#79]
I'm seeing IL on ign.com now.

**Comment by gorhill** [comment]
I am unable to see IL, also if using a US VPN.

How did you come to the conclusion IL is used?

**Comment by pishposhmcgee** [comment]
I'm seeing it here: http://www.ign.com/wikis/new-super-mario-bros-2
Possibly it is only enabled on portions of the site thus far.

**Comment by pishposhmcgee** [comment]
Here's a screenshot when I visit the home page
![screenshot from 2018-01-15 00-24-21](https://user-images.githubusercontent.com/5084679/34929652-b63ab9a6-f98a-11e7-8782-9b7caee1e5ea.png)

**Comment by Hitechcomputergeek** [comment]
I am also seeing Instart Logic code on IGN - when I click "view source", right there at the top is "Copyright Instart Logic Tue Feb 27 2018 - version: 10.1.4". I am in the US and using Chromium 60. I see Instart Logic code on the homepage as well as articles, even after clearing all cookies and local storage.

**Comment by okiehsch** [comment]
I can reproduce with a US IP address.
