### ISSUE TITLE
mmo-champion.com and all other curse sites

### ISSUE THREAD

**Issue by uboextrauser** [gorhill/uBO-Extra#81]
Hi, there is new script with ads spam in console:
![image](https://user-images.githubusercontent.com/35837743/35438217-120d0b76-02af-11e8-8466-c0a76810f3b1.png)

here:
https://www.curseforge.com/wow/addons
https://www.mmo-champion.com/content/
and all other curse sites

This script:
https://cdm.cursecdn.com/js/curseforge/cdmfactorem_min.js from curseforge
https://cdm.cursecdn.com/js/mmo-champion/16.5.3-adf1ht1/cdmfactorem_min.js from mmo-champion

But I don't see any ads, just this spam in console, can you block it?

There is two issues about this scripts already:
https://github.com/uBlockOrigin/uAssets/issues/1280
https://github.com/uBlockOrigin/uAssets/issues/72

I have uBlock Origin 1.14.24 and uBlock Origin Extra 2.61 on Google Chrome 64.0.3282.119

**Comment by gorhill** [comment]
Console output is out of scope of this project.

**Comment by uBlock-user** [comment]
you can add it yourself

`cdmfactorem_min.js$script,domain=mmo-champion.com|curseforge.com`
