### ISSUE TITLE
Black glitches watching twitch.tv vods at 60fps

### ISSUE THREAD

**Issue by Wabbitface** [gorhill/uBO-Extra#86]
Disabling uBlock Origin Extra fixes the problem. With the chrome extension enabled, videos look like this on Twitch.tv:
https://i.imgur.com/asuPSRO.gifv

Here is a link to my vod, you should be able to replicate it with the extension on:
https://www.twitch.tv/videos/243378587

I got to admit, this was really strange for me to crack down, finally glad to find the culprit to this weird bug.

Edit: forgot to specify - chrome extension.

**Comment by gorhill** [comment]
Unable to reproduce, and it's not surprising: that extension does **nothing** on Twitch, it's a no-op, it does something only for the [sites listed here](https://github.com/gorhill/uBO-Extra/wiki/Sites-on-which-uBO-Extra-is-useful).

Something else is causing this on your side.
