### ISSUE TITLE
vg.no

### ISSUE THREAD

**Issue by SkeletalDemise** [gorhill/uBO-Extra#87]
Uses Instart Logic.
Test Link: https://www.vg.no
Screenshot of g00 obfuscation:
![vg no instart logic](https://user-images.githubusercontent.com/29117662/38289414-e29cd98c-378a-11e8-82e8-465b33f13df3.png)

**Comment by gorhill** [comment]
Can you validate it fixes the issue by installing from source? <https://github.com/gorhill/uBO-Extra/releases/tag/2.65>.

**Comment by SkeletalDemise** [comment]
Yes, it appears to fix it. I cannot reproduce with 2.65.
