### ISSUE TITLE
Improve description

### ISSUE THREAD

**Issue by rehfeldchris** [gorhill/uBO-Extra#88]
First, thanks for the great extension.

If you want usage of your extension to grow more mainstream, I think improving the extension description would significantly help. I think the description's target audience should focus mainly on regular, non-technical / non-programmer users. You can then provide links to more technical details for those who wish to pursue it.

While I understand what this extension does, more or less, I bet very few non-programmers do. I think the extension description could benefit from some extra explanation - what it does in simple terms, what benefits will the user get by using it, why someone might want to use it - in terms regular users easily understand.

Also, you should clarify Instart Logic is a "bad" company that advertisers work with / use, and that it causes a problem that your extension aims to solve. Most users can't infer that they're "bad" from the 1st party / 3rd party cookie explanation. In fact, currently it almost sounds like you might be touting your own tech.

**Comment by gorhill** [comment]
> If you want usage of your extension to grow more mainstream

That's not my goal at all. That's should never be brought as something I care about. My goal is to make the tools I provide -- for whoever care to use them -- perform their duty as best as possible.

I think the summary description is just fine:

> to gain ability to foil early hostile anti-user mechanisms working around content blockers.
