### ISSUE TITLE
Newsweek.com appears to be using Instart Logic

### ISSUE THREAD

**Issue by pishposhmcgee** [gorhill/uBO-Extra#91]
See for example http://www.newsweek.com/customs-and-border-control-beat-kicked-and-threatened-migrant-children-under-941385 from U.S. IP address
![newsweek-instartlogic](https://user-images.githubusercontent.com/5084679/40596971-05e76fa8-6204-11e8-9c08-42b7dc1f6f61.png)

**Comment by okiehsch** [comment]
`newsweek.com` has already been added to the [contentscript]( https://github.com/gorhill/uBO-Extra/commit/5570dc08c58e2c4a4b569589016ded95d910a09a).
It will be fixed  as soon as gorhill releases uBO-Extra 2.71

**Comment by pishposhmcgee** [comment]
Ah, I missed that. Thanks.
