### ISSUE TITLE
Stopped working on kissanime.ru

### ISSUE THREAD

**Issue by WiseSilverWolf** [gorhill/uBO-Extra#94]
Hey guys,
I just wanted to let you know that uBlock Origin Extra 2.73 (for Chrome) stopped working on the popular anime streaming website named kissanime.ru, I was trying to stream an anime titled "Flying Witch (Dub)" and I got this message:

**"Please disable AdBlock (or any ads blocking) to watch anime on KissAnime. You have just been banned for a few days because of this."**

I didnt receive this message before, it always blocked ads on that site without any issues.

This is my info:

Chrome Version: 67.0.3396.99 (Official Build) (64-bit)
uBlock Origin 1.16.10
uBlock Origin Extra 2.73
OS: Windows 10 (64-bit)

Thank you

**Comment by gorhill** [comment]
`kissanime.ru` has never been a target of uBO-Extra. Report your issue to filter list maintainers.

**Comment by gorhill** [comment]
https://github.com/uBlockOrigin/uAssets/issues/2719
