### ISSUE TITLE
mysanantonio.com

### ISSUE THREAD

**Issue by terrorist96** [gorhill/uBO-Extra#97]
See https://github.com/uBlockOrigin/uAssets/issues/3225

**Comment by ghajini** [comment]
page source code>
`https://pastebin.com/ZhnF93jK`

**Comment by okiehsch** [comment]
A US Ip is e´needed to reproduce on my end.

**Comment by gorhill** [comment]
I will publish an official 2.76 version once I am satisfied that the issues currently being worked on are all confirmed to be resolved.
