### ISSUE TITLE
ads show on nasdaq.com

### ISSUE THREAD

**Issue by pfgithub** [gorhill/uBO-Extra#98]

**Comment by ghajini** [comment]
instart logic/g00
@gorhill

**Comment by ghajini** [comment]
Anybody interested ? Or this repo is dead, IAM not spamming

**Comment by okiehsch** [comment]
I already said that not everbody can reproduce, so what exactly should gorhill do in your opinion?

For the record I can not reproduce any ads or redirection at `nasdaq.com` with `uBO-extra` enabled.

**Comment by ghajini** [comment]
I tried on standard setup(ublock origin+ubo extra) 
&even creating new chrome profile, I can consistently reproduce on listed sites...

Can you try on new chrome profile with ublock origin & ubo extra only

**Comment by gorhill** [comment]
Please see if 2.76 helps.

**Comment by pfgithub** [comment]
I don't think there ever were ads on nasdaq.com, when I opened this issue I must have mistaken the flashy looking things on the sidebar for ads.
